### ISSUE TITLE
cutadapt-1.7 build fails

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#101]
_From [giuseppe...@gmail.com](https://code.google.com/u/106167236156727236905/) on November 25, 2014 19:55:42_

This is what happened on my system

$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 91, in \<module>
    extensions = cythonize_if_necessary(extensions)
  File "setup.py", line 64, in cythonize_if_necessary
    elif out_of_date(extensions):
  File "setup.py", line 35, in out_of_date
    os.path.getmtime(pyx) > os.path.getmtime(csource)):
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'cutadapt/_align.pyx'

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=91_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on November 25, 2014 11:09:17_

You are right, a change I made to the setup.py file caused the .pyx files not to be included anymore (which wasn't visible during testing).

I've uploaded cutadapt 1.7.1, which includes the files. Please tell me if it works. Thanks for reporting this!

**Status:** Accepted

**Comment by marcelm** [comment]
_From [sh...@biomatters.com](https://code.google.com/u/112850672763939071043/) on November 25, 2014 11:16:25_

I was just wrestling with this issue on my CentOS 6.6 build machine and can confirm that 1.7.1 now builds fine.

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on November 26, 2014 01:51:31_

Thanks for the feedback and sorry for the trouble. I've updated the homepage to point people to the 1.7.1 release.

**Status:** Fixed

**Comment by marcelm** [comment]
_From [giuseppe...@gmail.com](https://code.google.com/u/106167236156727236905/) on November 26, 2014 02:04:30_

I confirm that now it builds fine. Thank you!
