### ISSUE TITLE
better error reporting on parse errors

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#23]
_From [gregorym...@gmail.com](https://code.google.com/u/106214861038465729515/) on March 18, 2011 00:29:09_

What steps will reproduce the problem? 1. I downloaded the latest version
2. cutadapt -O 10 -b CAGACGTGCCTCACTACGT TEE.TEST.fastq > TEE.test.trim.a1.fastq             (TEE.TEST.fastq is just a standard fastq file) What is the expected output? What do you see instead? Trimmed sequences with statistics.

[kumarlab@BatLC1 TEE]$ cutadapt -O 10 -b CAGACGTGCCTCACTACGT TEE.TEST.fastq > TEE.test.trim.a1.fastq
Traceback (most recent call last):
  File "/home/kumarlab/bioinfo/cutadapt-0.9.3/cutadapt", line 549, in \<module>
    sys.exit(main())
  File "/home/kumarlab/bioinfo/cutadapt-0.9.3/cutadapt", line 508, in main
    for desc, seq, qualities in reader:
  File "/home/kumarlab/bioinfo/cutadapt-0.9.3/lib/cutadapt/seqio.py", line 196, in __iter__
    assert line[0] == '@'
AssertionError What version of the product are you using? On what operating system? 0.9.3 on linux Please provide any additional information below. I have performed this operation many times before.  I got a new server and installed the latest version of cutadapt and encountered this problem.

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=13_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on March 18, 2011 00:57:32_

Could you please send me (or attach to this issue) the first few lines of the TEE.TEST.fastq file?

**Comment by marcelm** [comment]
_From [gregorym...@gmail.com](https://code.google.com/u/106214861038465729515/) on March 18, 2011 11:15:13_

Cutadapt runs and removes the adapter sequence but does not report statistics.

**Attachment:** [TEE.TEST.fastq](http://code.google.com/p/cutadapt/issues/detail?id=13#hc2)

**Comment by marcelm** [comment]
_From [gregorym...@gmail.com](https://code.google.com/u/106214861038465729515/) on March 18, 2011 11:26:06_

The issue must have been with that file, when I ran it with the full data set it worked fine.  Sorry to have bothered you.  Thank you for your help.

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on March 18, 2011 14:27:56_

No need to be sorry, cutadapt could at least give a better error message. It seems that your test file contains two unexpected empty lines in the end, and this must have caused the assertion error. I will leave this issue open until I have added better error reporting to the routines that read in FASTQ files.

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on March 18, 2011 14:28:51_

**Summary:** better error reporting on parse errors

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on April 20, 2011 09:50:08_

This issue was closed by revision r133 .

**Status:** Fixed

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on April 20, 2011 09:52:04_

I've added some slightly better error reporting. Now cutadapt reports this when confronted with your file:
Error: at line 253, expected a line starting with '+'

**Comment by marcelm** [comment]
_From [gregorym...@gmail.com](https://code.google.com/u/106214861038465729515/) on April 20, 2011 09:55:53_

Thanks!  Much appreciated.
