### ISSUE TITLE
error with multiple linked adapters

### ISSUE THREAD

**Issue by markschl** [marcelm/cutadapt#265]
When trying to match multiple adapters I encountered a problem. I haven't examined why it occurs, but I managed to reduce it to a small example that shows the same problems as the real data:
```python
cutadapt -g ATGC...ATGC -g AGGC...RYGC test.fa
```
returns 
```
This is cutadapt 1.14 with Python 2.7.3
Command line parameters: -g ATGC...ATGC -g AGGC...RYGC test.fa
Trimming 2 adapters with at most 10.0% errors in single-end mode ...
Traceback (most recent call last):
  File "[...]/.local/bin/cutadapt", line 9, in <module>
    load_entry_point('cutadapt==1.14', 'console_scripts', 'cutadapt')()
  File "[...]/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 779, in main
    stats = pipeline.run()
  File "[...]/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 127, in run
    (n, total1_bp, total2_bp) = self.process_reads()
  File "[...]/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 156, in process_reads
    read = modifier(read)
  File "[...]/.local/lib/python2.7/site-packages/cutadapt/modifiers.py", line 120, in __call__
    match = self._best_match(trimmed_read)
  File "[...]/.local/lib/python2.7/site-packages/cutadapt/modifiers.py", line 74, in _best_match
    if best is None or match.matches > best.matches:
  File "[...]/.local/lib/python2.7/site-packages/cutadapt/adapters.py", line 596, in matches
    m += self.back_match.matches
TypeError: 'int' object is not iterable
```
The contents of `test.fa` are 
```
>seq1
ATGCSOMESEQATGC
```

**Comment by marcelm** [comment]
Thanks for this very nice bug report! I’ve fixed the problem now. It occured when trimming multiple adapters of which one is an unanchored linked adapter (`-g`) and if the 5' end of that adapter does not match a read.

I’m not sure if the changes so far warrant a new release, but until then, you can install from the repository.

**Comment by markschl** [comment]
Thank you very much!

**Comment by marcelm** [comment]
You’re welcome! Sure, if you can use an anchored adapter instead, then this would be a good way to avoid the bug in this version.
