### ISSUE TITLE
Cannot run cutadapt on Windows 10 computer

### ISSUE THREAD

**Issue by EfrahY** [marcelm/cutadapt#315]
I was able to sucessfully install cutadapt (1.16) using pip and python (3.6) on a Windows 10 computer. However, when trying to run cutadapt, I received the following error message: **_ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr._** This message also appears when using Python 2.7 on another Windows computer.

Your help would be much appreciated!

Traceback (most recent call last):
  File "C:\Users\Student\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Student\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Users/Student/AppData/Roaming/Python/Python36/site-packages/cutadapt\__main__.py", line 769, in <module>
    main()
  File "C:/Users/Student/AppData/Roaming/Python/Python36/site-packages/cutadapt\__main__.py", line 689, in main
    outfiles = open_output_files(options, default_outfile, is_interleaved_output)
  File "C:/Users/Student/AppData/Roaming/Python/Python36/site-packages/cutadapt\__main__.py", line 412, in open_output_files
    out, out2 = open2(options.output, options.paired_output)
  File "C:/Users/Student/AppData/Roaming/Python/Python36/site-packages/cutadapt\__main__.py", line 366, in open2
    file1 = xopen(path1, 'w')
  File "C:\Users\Student\AppData\Roaming\Python\Python36\site-packages\xopen.py", line 244, in xopen
    return PipedGzipWriter(filename, mode)
  File "C:\Users\Student\AppData\Roaming\Python\Python36\site-packages\xopen.py", line 74, in __init__
    self.process = Popen(['pigz'], **kwargs)
  File "C:\Users\Student\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 624, in __init__
    "close_fds is not supported on Windows platforms"
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

**Comment by marcelm** [comment]
I’m sorry, but I don’t support or test Cutadapt on Windows. It is interesting to hear that it “nearly” works, though.

If you want to get it to run, you are somewhat on your own. I would attempt to modify the `xopen.py` file at `C:\Users\Student\AppData\Roaming\Python\Python36\site-packages\xopen.py` in which the error occurs. Search for this line:
```
kwargs = dict(stdin=PIPE, stdout=self.outfile, stderr=self.devnull, close_fds=True)
```
and replace it with:
```
kwargs = dict(stdin=PIPE, stdout=self.outfile, stderr=self.devnull)
```
If I remember correctly, the `close_fds` parameter may not be strictly necessary, so the program should still work (but remember this modification if anything weird happens).

**Comment by EfrahY** [comment]
It worked - thank you for your speedy response!

**Comment by marcelm** [comment]
Cool, thanks for letting me know. I think I’ll just build this into the script. It will detect whether it’s running on Windows and then omit the `close_fds` parameter.

**Comment by marcelm** [comment]
Here is the change I made: https://github.com/marcelm/xopen/commit/6aa155d4c93b5ec2b19463e72beea1a60a1cd82b

**Comment by kuttibiotech2009** [comment]
Similar error me also getting please help me.....
Traceback (most recent call last):
  File "c:\users\kutti\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kutti\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kutti\AppData\Local\Programs\Python\Python37\Scripts\cutadapt.exe\__main__.py", line 5, in <module>
  File "c:\users\kutti\appdata\local\programs\python\python37\lib\site-packages\cutadapt\__main__.py", line 71, in <module>
    from cutadapt.report import full_report, minimal_report
  File "c:\users\kutti\appdata\local\programs\python\python37\lib\site-packages\cutadapt\report.py", line 10, in <module>
    from .filters import (NoFilter, PairedNoFilter, TooShortReadFilter, TooLongReadFilter,
  File "c:\users\kutti\appdata\local\programs\python\python37\lib\site-packages\cutadapt\filters.py", line 21, in <module>
    from .utils import raise_open_files_limit
  File "c:\users\kutti\appdata\local\programs\python\python37\lib\site-packages\cutadapt\utils.py", line 4, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

**Comment by marcelm** [comment]
Please see issue #404. In short: Use Cutadapt 2.4 for now. Cutadapt 2.6 (will be released soon) should work on Windows again.

**Comment by kuttibiotech2009** [comment]
Thank you so much sir

seems it working but i am getting message like this

C:\Users\kutti>cutadapt
This is cutadapt 2.4 with Python 3.7.4
Command line parameters:
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: You did not provide any input file names. Please give me something to do!

**Comment by kuttibiotech2009** [comment]
C:\Users\kutti>cutadapt -a AACCGGTT -o OBF16_R1.fastq BF16_R1.fastq
This is cutadapt 2.4 with Python 3.7.4
Command line parameters: -a AACCGGTT -o BFA16_R1.fastq BF16_R1.fastq
Processing reads on 1 core in single-end mode ...

No reads processed!

**Comment by marcelm** [comment]
> No reads processed!

Cutadapt prints this message when the input file (`BF16_R1.fastq`) contains no reads. Did you make a mistake when specifying which input file to use? Can you check the file size of `BF16_R1.fastq`? If it is zero bytes, then that is the problem.

**Comment by kuttibiotech2009** [comment]
yes, sir, there was a problem with file location.....when I change it... its start working

I changed like this

C:\Users\kutti>cd/
C:\>cd C:\Users\kutti\AppData\Local\Programs\Python\Python37\Lib\site-packages
C:\Users\kutti\AppData\Local\Programs\Python\Python37\Lib\site-packages>cutadapt -a AACCGGTT -o BOF16_R2.fastq.gz BF16_R2.fastq.gz

**Comment by kuttibiotech2009** [comment]
Thank you sir
Your suggestion helped me a lot 

I have one more doubt sir,

Further, I want to remove low-quality reads using sickle..... but i don't know whether we can run with windows 10 or not.....
Please help me to find out the ways to run it

Sincerely
KUTTI

**Comment by marcelm** [comment]
Great, glad it worked. Regarding your other question: I can only help with Cutadapt-related things, sorry!

**Comment by kuttibiotech2009** [comment]
Thank you so much sir...

Sincerely
KUTTI R
