### ISSUE TITLE
v2.0: AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by ptrebert** [marcelm/cutadapt#371]
Hi,
cutadapt: 2.0
Python: 3.6.7
Call: `-j 2 -e 0.1 -q 20 -O 1 --trim-n -a AGATCGGAAGAGC PATH_OMITTED`

Setup was via conda/miniconda 4.6.7, and I am trying to run `trim_galore v0.6.1_dev`. The execution leads to the following error:

```
Processing reads on 2 cores in single-end mode ... 
Traceback (most recent call last):
  File "/CONDA/ENV/bin/cutadapt", line 12, in <module>
    sys.exit(main())
  File "/CONDA/ENV/lib/python3.6/site-packages/cutadapt/__main__.py", line 787, in main
    stats = runner.run()
  File "/CONDA/ENV/lib/python3.6/site-packages/cutadapt/pipeline.py", line 684, in run 
    raise e
AttributeError: 'str' object has no attribute 'name'
```

Best,
Peter

**Comment by marcelm** [comment]
Please upgrade to Cutadapt 2.1 - it contains the fix for this problem (see also issue #366).
