### ISSUE TITLE
Sequence and quality different lengths

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#39]
_From [plat...@sbcglobal.net](https://code.google.com/u/101478673082790728242/) on October 05, 2011 14:53:57_

Hi Marcel,

The below sounds like issue `#9` , but with colour space fastq data.

My problem is that the quality and sequence strings are not seen as being the same length, although they appear to be when I check them.

I am running 0.9.5 with python2.7 on 64bit CentOS (RedHat).

My command line is taken from novoalign's guide:

cutadapt -c -e 0.12 -a 330201030313112312  test.fastq

The output is:

Traceback (most recent call last):
  File "/opt/python2.7/bin/cutadapt", line 600, in \<module>
    sys.exit(main())
  File "/opt/python2.7/bin/cutadapt", line 548, in main
    for desc, seq, qualities in reader:
  File "/opt/python2.7/lib/python2.7/site-packages/cutadapt/seqio.py", line 239, in __iter__
    raise ValueError("Length of quality sequence and length of read do not match (&#37;d+&#37;d!=&#37;d)" &#37; (len(qualities), lengthdiff, len(sequence)))
ValueError: Length of quality sequence and length of read do not match (36+1!=36)

I then tried dos2unix test.fastq, but received the same result.

The test file is as below (this was generated using the fastq-dump tool from the SRA package so I'm unsure what line terminators are used but after dos2unix vi shows a $ at the end of each line in set list mode):

[aplatts@grandiflora novoalignCS]$ cat test.fastq
@SRR040402.1 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_192_F3 length=35
T32113113220300030.1232...32.2010...
+SRR040402.1 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_192_F3 length=35
!/?)>7;<<)/688(<+&!75)1!!!&&#37;!/3,/!!!
@SRR040402.2 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_295_F3 length=35
T33213022233231303.2000...20.2203...
+SRR040402.2 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_295_F3 length=35
!)&4,6):-7'&5+$*)8!'&&5!!!(3!)&4&!!!
@SRR040402.3 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_298_F3 length=35
T33211222202311330.0000...30.2002...
+SRR040402.3 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_298_F3 length=35
!*##,.)&#37;)*&&048$&#37;&!2&+&#37;!!!&#37;(!&-/+!!!
@SRR040402.4 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_316_F3 length=35
T22213010112010010.3113...33.1111...
+SRR040402.4 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_316_F3 length=35
!)8)&#37;+.9,4669/$#52!1&#37;,3!!!'5!1,&#37;+!!!
@SRR040402.5 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_578_F3 length=35
T00112130221210101.2010...13.1111...
+SRR040402.5 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_578_F3 length=35
!(//8&/(;(,>))(&1(!99<8!!!50!.)&6!!!
@SRR040402.6 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_693_F3 length=35
T01200230113010033.2131...20.1003...
+SRR040402.6 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_693_F3 length=35
!<*5((((6)5181&41#!-)()!!!'*!5.6#!!!
@SRR040402.7 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_714_F3 length=35
T23211301211022321.1322...20.1123...
+SRR040402.7 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_714_F3 length=35
!:27=43=:5<6;9;/49!-(8:!!!/6!+2&.!!!
@SRR040402.8 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_728_F3 length=35
T10203211202030103.3112...21.1122...
+SRR040402.8 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_728_F3 length=35
!;,6(.1)($1(9#&#/8!,)-)!!!*3!00(3!!!
@SRR040402.9 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_756_F3 length=35
T33220333011333332.2210...30.0013...
+SRR040402.9 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_756_F3 length=35
!5(19<63/8:<7.1&#37;1'!.,35!!!+6!).*/!!!
@SRR040402.10 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_1009_F3 length=35
T01211220222221112.1222...03.1011...
+SRR040402.10 VAB_sparrow_20091211_2_Axtell_smallRNA2_and_transcriptome6_bc1to82_18_1009_F3 length=35
!&/,;6&)/2,,/78,,;!/)1:!!!&#!193/!!!

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=29_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on October 06, 2011 08:28:37_

Ah, sorry, this is actually a known issue, but it's only mentioned in the README file:
"SRA color space FASTQ files include a quality for the initial nucleotide, this is not handled correctly"

So, for color space data, cutadapt actually expects that there's one less character in the quality string than there are characters in the read. That's how the original SOLiD data output looks like since the initial "T" isn't really sequenced, so no quality value for it is actually known.

This should be easy to fix but since I'm currently on the road, it may take a bit.

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on June 17, 2012 11:05:26_

I have now added a new input format "sra-fastq". When you want to work with those SRA that contain the additional initial quality, simply add "--format sra-fastq" to the cutadapt command line. The fake quality character will be removed from *all* output reads.

The new input format will be available in cutadapt 1.1.

**Status:** Fixed
