### ISSUE TITLE
problem with configuring cutadapt

### ISSUE THREAD

**Issue by gdaniella** [marcelm/cutadapt#404]
Hi, 
A little new to this. Have been trying to follow DADA2's ITS pipeline which requires cutadapt. Have installed python (v3.7.4), and used pip to install cutadapt (v2.5):
`pip install cutadapt`
received the following:
```
Collecting cutadapt
Requirement already satisfied: xopen~=0.8.1 in c:\users\mine\appdata\local\programs\python\python37\lib\site-packages (from cutadapt) (0.8.2)
Requirement already satisfied: dnaio~=0.3.0 in c:\users\mine\appdata\local\programs\python\python37\lib\site-packages (from cutadapt) (0.3)
Installing collected packages: cutadapt
Successfully installed cutadapt-2.5
```
However, when typing `cutadapt` on the cmd, getting this massage:
`Traceback (most recent call last):
  File "c:\users\mine\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mine\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mine\AppData\Local\Programs\Python\Python37\Scripts\cutadapt.exe\__main__.py", line 5, in <module>
  File "c:\users\mine\appdata\local\programs\python\python37\lib\site-packages\cutadapt\__main__.py", line 71, in <module>
    from cutadapt.report import full_report, minimal_report
  File "c:\users\mine\appdata\local\programs\python\python37\lib\site-packages\cutadapt\report.py", line 10, in <module>
    from .filters import (NoFilter, PairedNoFilter, TooShortReadFilter, TooLongReadFilter,
  File "c:\users\mine\appdata\local\programs\python\python37\lib\site-packages\cutadapt\filters.py", line 21, in <module>
    from .utils import raise_open_files_limit
  File "c:\users\mine\appdata\local\programs\python\python37\lib\site-packages\cutadapt\utils.py", line 4, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'`
 Expected to get a list of arguments, general info, etc. 
And when running [DADA2 pipeline](https://benjjneb.github.io/dada2/ITS_workflow.html) R cannot call on cutadapt and no output is produced.

Thanks so much for your help

**Comment by marcelm** [comment]
Indeed, it appears as if he `resource` module is not available on Windows. I don’t test Cutadapt on Windows, so haven’t noticed this.

I can fix this so that the module is not used on Windows. Until then, you can just use Cutadapt 2.4 instead. It doesn’t need the resource module.

**Comment by marcelm** [comment]
I’ve fixed the problem now.

**Comment by marcelm** [comment]
And for others finding this issue: Use `pip install cutadapt==2.4` to get version 2.4.
