### ISSUE TITLE
'PipedGzipReader' object has no attribute 'seekable'

### ISSUE THREAD

**Issue by mlesche** [marcelm/cutadapt#421]
Dear All,

I'm running trim_galore and getting this error for cutadapt

This is cutadapt 2.3 with Python 3.7.0
Command line parameters: -f fastq -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC fastq_split/L45636_DP325PD01_Track-82227-82262_R1.fastq_0047.gz
WARNING: Option --format is deprecated and ignored because the input file format is always auto-detected
Traceback (most recent call last):
  File "/share/apps/cutadapt/2.3/bin/cutadapt", line 11, in <module>
    load_entry_point('cutadapt==2.3', 'console_scripts', 'cutadapt')()
  File "/share/apps/cutadapt/2.3/venv/lib/python3.7/site-packages/cutadapt/__main__.py", line 796, in main
    runner = runner_class(pipeline, infiles, outfiles, **runner_kwargs)
  File "/share/apps/cutadapt/2.3/venv/lib/python3.7/site-packages/cutadapt/pipeline.py", line 723, in __init__
    self._pipeline.set_input(infiles)
  File "/share/apps/cutadapt/2.3/venv/lib/python3.7/site-packages/cutadapt/pipeline.py", line 110, in set_input
    interleaved=infiles.interleaved, mode='r')
  File "/share/apps/cutadapt/2.3/venv/lib/python3.7/site-packages/dnaio/__init__.py", line 83, in open
    file1, fileformat=fileformat, mode=mode, qualities=qualities)
  File "/share/apps/cutadapt/2.3/venv/lib/python3.7/site-packages/dnaio/__init__.py", line 148, in _open_single
    if file.seekable():
AttributeError: 'PipedGzipReader' object has no attribute 'seekable'

My command line is:
trim_galore --paired --dont_gzip --output_dir . -q 20 fastq_split/L45636_DP325PD01_Track-82227-82262_R1.fastq_0047.gz fastq_split/L45636_DP325PD01_Track-82227-82262_R2.fastq_0047.gz

and trim_galore is using
cutadapt 2.3 and python 3.7.0

I believe the Error is referring to the xopen module but I'm not quite sure. I can't really tell who this was installed because the tools are on our cluster and were installed by the admins.

**Comment by marcelm** [comment]
Yes, this is a bug in the `xopen` library. Please tell your admins to upgrade xopen to at least version 0.7.1 (and while they’re upgrading anyway, they could also install a newer Cutadapt version).

**Comment by mlesche** [comment]
Hey Marcel,

Thanks for the quick reply. I'll tell him :)

**Comment by marcelm** [comment]
No problem! I’m closing this issue now, but if the upgrade doesn’t fix it, just comment here and I’ll re-open it.
