### ISSUE TITLE
--info-file results in 'LinkedMatch' object has no attribute 'get_info_record'

### ISSUE THREAD

**Issue by Citteny** [marcelm/cutadapt#431]
Hi continuing  #430
_The goal is to get the trimmed sequence_

I'm using `linked adapters`, and encountered a problem using the info file option.
i'm using cutadapt 2.7 (pip installation), Python 3.6.0

**The command:**
```cutadapt -a "XNNNCAATAGCATGCCTTGCCGATTTGTCATC...AGATGGGGGGAAACAAANNNNX" --info-file info.txt  merged_fq.fastq ```

**Content of merged_fq.fastq:**
```
@A00197:84:HHGW7DMXX:1:1102:28501:3505 1:N:0:TTACCGAC+CCTATCCT
ACACAATAGCATGCCTTGCCGATTTGTCATCTTTTCCAGTTCTTTAGTATCATGATTTATAGCATCCATATGTTCTTTTTCCATATTTTTCCAGCGCTCCATACTCTTCTGAAGCTCCTTAATTCCAGCTTCTGTTTTATCAATGGAATTGTCCAAATCTAAGATGGGGGGAAACAAAATTG
+
FFFFFFFFFFFFFFFFFFFFF:,:FFFFFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJHJJJJJJJJJJJJHJJJJJJJJJJJJJJJJJJJJJJJJJJJJ@JJJJHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```
**Traceback:**

```
This is cutadapt 2.7 with Python 3.6.0
Command line parameters: -a XNNNCAATAGCATGCCTTGCCGATTTGTCATC...AGATGGGGGGAAACAAANNNNX --info-file info.txt merged_fq.fastq
Processing reads on 1 core in single-end mode ...
Traceback (most recent call last):
  File "/usr/.venvs/lsl/bin/cutadapt", line 8, in <module>
    sys.exit(main())
  File "/usr/.venvs/lsl/lib/python3.6/site-packages/cutadapt/__main__.py", line 825, in main
    stats = runner.run()
  File "/usr/.venvs/lsl/lib/python3.6/site-packages/cutadapt/pipeline.py", line 758, in run
    (n, total1_bp, total2_bp) = self._pipeline.process_reads(progress=self._progress)
  File "/usr/.venvs/lsl/lib/python3.6/site-packages/cutadapt/pipeline.py", line 266, in process_reads
    if filter_(read, matches):
  File "/usr/.venvs/lsl/lib/python3.6/site-packages/cutadapt/filters.py", line 91, in __call__
    if self.filter(read, matches):
  File "/usr/.venvs/lsl/lib/python3.6/site-packages/cutadapt/filters.py", line 409, in __call__
    info_record = match.get_info_record()
AttributeError: 'LinkedMatch' object has no attribute 'get_info_record'

```
Changed my path to "usr" for simplification.
Trimming is working fine without "--info-file " option.

Thank you

**Comment by marcelm** [comment]
Yes, this is similar to #430. I’ll look into this as soon as I have time.

**Comment by marcelm** [comment]
This is now also fixed: Linked adapters will now be shown in the info file (one row for each of the two parts). Again, thanks for reporting!

**Comment by Citteny** [comment]
OMG, Thank you so much!
This tools is amazing!
