### ISSUE TITLE
issue with cutadapt installation

### ISSUE THREAD

**Issue by DenisGoryunov** [marcelm/cutadapt#432]
Hi,
I tried to install cutadapt with command(i already have an older version at ~/.local/bin/) at my home on HPC ubuntu cluster:
 python -m pip install --user --upgrade cutadapt

I got error message :

"Traceback (most recent call last):
  File "/home/tools/python/Python-2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/home/tools/python/Python-2.7/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/home/tools/python/Python-2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/home/tools/python/Python-2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/home/tools/python/Python-2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/home/tools/python/Python-2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/home/tools/lib/python2.7/site-packages/pip/__init__.py", line 18, in <module>
    from pip.commands import get_summaries, get_similar_commands
  File "/home/tools/lib/python2.7/site-packages/pip/commands/__init__.py", line 8, in <module>
    from pip.commands.freeze import FreezeCommand
  File "/home/tools/lib/python2.7/site-packages/pip/commands/freeze.py", line 8, in <module>
    from pip.operations.freeze import freeze
RuntimeError: unable to get file status from '/home/tools/lib/python2.7/site-packages/pip/operations/__init__.py'"

Could you help me to fix it please?

Many thanks,
Denis

**Comment by marcelm** [comment]
Cutadapt no longer supports Python 2.7, so I suggest you try with Python 3. Use the same command, but write `python3` instead of `python`.

**Comment by marcelm** [comment]
I hope you got it to work. I an also recommend trying Bioconda if there’s still a problem.

**Comment by DenisGoryunov** [comment]
Hi,
Thank you very much for your help. I apology for the late reply. The following solution was working for me:
 1)module load python/python-3.7.4
2)python3 -m pip install --user --upgrade cutadapt

I'm wondering should i load module python-3.7.4 each time before cutadapt executing, i.e. :
1)module load python/python-3.7.4 # load python 3.7.4.
2)  ~/.local/bin/cutadapt   # cutadapt running

Regards,
Denis

**Comment by marcelm** [comment]
Hi, thanks for getting back. The command that you used sounds correct to me, good that you figured it out.

It should not be necessary to load the python/python-3.7.4 module before running Cutadapt.
