### ISSUE TITLE
cutadapt work with fasta and qual file paires

### ISSUE THREAD

**Issue by xiaoli-dong** [marcelm/cutadapt#433]
"cutadapt -e 0 --quiet -j 1  -g ^CCTACGGGAGGCAGCAG --discard-untrimmed  -o test.trim.fastq test.fasta"

My input to the cutadapt is test.fasta and I have test.qual file in the same directory. I want to use cutadapt to trim adapter and write the output as fastq format. I was running the above command and get the following errors:
``` 
-bash-4.2$ cutadapt -e 0 --quiet -j 1  -g ^CCTACGGGAGGCAGCAG --discard-untrimmed  -o test.trim.fastq test.fasta 
Traceback (most recent call last):
  File "/gpfs/ebg_data/programs/cutadapt/bin/cutadapt", line 8, in <module>
    sys.exit(main())
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/cutadapt/__main__.py", line 816, in main
    runner = runner_class(pipeline, infiles, outfiles, progress, **runner_kwargs)
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/cutadapt/pipeline.py", line 755, in __init__
    self._pipeline.connect_io(infiles, outfiles)
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/cutadapt/pipeline.py", line 118, in connect_io
    self._set_output(outfiles)
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/cutadapt/pipeline.py", line 194, in _set_output
    self._filters.append(self._final_filter(outfiles))
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/cutadapt/pipeline.py", line 278, in _final_filter
    writer = self._open_writer(outfiles.out, force_fasta=outfiles.force_fasta)
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/cutadapt/pipeline.py", line 130, in _open_writer
    **kwargs)
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/dnaio/__init__.py", line 109, in open
    file1, opener=opener, fileformat=fileformat, mode=mode, qualities=qualities)
  File "/gpfs/ebg_data/programs/cutadapt/lib/python3.6/site-packages/dnaio/__init__.py", line 192, in _open_single
    'Output format cannot be FASTQ since no quality values are available.')
ValueError: Output format cannot be FASTQ since no quality values are available.
```

**Comment by marcelm** [comment]
Hi, Cutadapt no longer supports processing of `.fasta`/`.qual` files. If you need this functionality, please use the old version Cutadapt 1.18. See also [this note in the documentation](https://cutadapt.readthedocs.io/en/stable/colorspace.html#colorspace). (Support for `.qual` files existed only for working with colorspace data, so it got removed when support for colorspace was removed.)

When you do use that version, note that you will need to give the name of the `.qual` file explicitly as a separate argument. It will not be found automatically.
