### ISSUE TITLE
remove adaptor sequence

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#45]
_From [xinhui...@gmail.com](https://code.google.com/u/105968875265431851569/) on January 18, 2012 17:50:16_

Hi there, 
i run the cutadapt to remove adaptor sequence from RNA-SEQ data, but it gave me some error. could you please help me fix it? Thanks. 
Below is the error,

'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/opt/bioinf/bin/cutadapt", line 71, in \<module>
    _libdir = join(dirname(realpath(__file__)), 'lib')
  File "/usr/lib64/python2.6/posixpath.py", line 362, in realpath
    if islink(component):
  File "/usr/lib64/python2.6/posixpath.py", line 135, in islink
    return stat.S_ISLNK(st.st_mode)
AttributeError: 'module' object has no attribute 'S_ISLNK'

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=35_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on January 19, 2012 06:21:34_

Which command line did you run cutadapt with? Which operating system are you on?

Please run this on the command line:

python -c 'import os; print os.path.islink("/")'

It should simply print "False". If you get an error, is it the same as the one above?

**Comment by marcelm** [comment]
_From [reneex...@gmail.com](https://code.google.com/u/102696347309204774580/) on January 19, 2012 12:30:29_

Thanks for reply.
The command I run the cutadapt is, 
cutadapt -a GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCG Sample.fastq >  Sample_cut.fastq
The operating system is linux.
I also run the command line you mentioned, python -c 'import os; print os.path.islink("/")'
It shows the error, 
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "/usr/lib64/python2.4/posixpath.py", line 162, in islink
    return stat.S_ISLNK(st.st_mode)
AttributeError: 'module' object has no attribute 'S_ISLNK'


Could you please let me know which command I should run to cut the adaptor from RNA-SEQ data?
Thanks.

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on January 20, 2012 03:16:13_

There seems to be a problem with your installation. Please run this:

python -c 'import stat; print stat.__file__'

This should say something like /usr/lib64/python2.4/stat.py.

Have you modified your PYTHONPATH environment variable?

**Comment by marcelm** [comment]
_From [reneex...@gmail.com](https://code.google.com/u/102696347309204774580/) on January 20, 2012 10:20:35_

Thanks for your help.

When i run python -c 'import stat; print stat.__file__',
It says, 'import site' failed; use -v for traceback
/opt/bioinf/cistematic/3.0/stat/__init__.pyc

Do you how can I modify the PYTHONPATH environment variable?
Thanks,

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on January 20, 2012 10:39:44_

Ok, for some reasen, the module 'stat' from the cistematic package is being found instead of the 'stat' module that comes with Python. This isn't a cutadapt bug: It seems the cistematic package was installed incorrectly since it hides Python system modules. Do you have a system administrator you could ask about this? I'd ready to help a bit more, but I'd suggest to continue via e-mail.

You can print your PYTHONPATH environment variable with:
echo $PYTHONPATH

Interesting would also be this:
python -c 'import sys; print sys.path'

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on March 09, 2012 02:17:50_

I hope you were able to fix the problem. Since there weren’t any further messages regarding this problem and the problem was not with cutadapt, I’m closing this bug report.

**Status:** Invalid
