### ISSUE TITLE
error when using multicores

### ISSUE THREAD

**Issue by retrogenomics** [marcelm/cutadapt#495]
- Cutadapt 3.0, installed by pip; Python 3.8; pigz 2.4

Hi,
Using the following command:
```
cutadapt \
  --cores=2 \
  --nextseq-trim=20 \
  --minimum-length=36:189 \
  --trim-n \
  --discard-untrimmed \
  --action=none \
  -G a="^AAAAACTCCCTAACCCCTTA;e=0.15;o=5" \
  -o "R1.trimmed.fastq.gz" \
  -p "R2.trimmed.fastq.gz" \
  R1.fastq.gz \
  R2.fastq.gz
```
I got this type of error: 
``` 
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cutadapt/__main__.py", line 825, in main_cli
    main(sys.argv[1:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cutadapt/__main__.py", line 892, in main
    stats = r.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cutadapt/pipeline.py", line 793, in run
    workers, connections = self._start_workers()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cutadapt/pipeline.py", line 788, in _start_workers
    worker.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedWriter' object
```

However it is working smoothly if I remove the `--cores=2` argument.
I used this command line before in a script which was working fine with a previous version of cutadapt. Thus, it could be related to a recent change. Unfortunately I did not record which version it was.

Thanks for your help
-Gael

**Comment by marcelm** [comment]
This is very likely bug #469 that re-appeared. I’ll look into this.

**Comment by marcelm** [comment]
Since this is a macOS-specific problem, and I develop on Linux, I haven’t noticed this problem myself.

I have fixed the problem once more, and I have also set up automated tests for macOS, so hopefully something like this won’t happen again with future Cutadapt releases.

A workaround for the moment (apart from using `--cores=1`) is to downgrade to Python 3.7.

Thanks for reporting!

**Comment by retrogenomics** [comment]
Thanks for your quick answer and for developing and improving `cutadapt`. This is a great tool !
