### ISSUE TITLE
cutadapt -b crashes

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#50]
_From [modockes...@gmail.com](https://code.google.com/u/112757713298074552037/) on April 02, 2012 21:09:35_

cutadapt -b GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT 6_cutadap_trim_2.fastq -o recut_o -r recut_r --untrimmed-output=recut_untrim

  Traceback (most recent call last):
    File "/home/kesner/bin/python/bin/cutadapt", line 708, in \<module>
        sys.exit(main())
          File "/home/kesner/bin/python/bin/cutadapt", line 657, in main
              for read in reader:
                File "/home/kesner/bin/python/lib/python2.7/site-packages/cutadapt/seqio.py", line 249, in __iter__
                    raise ValueError("Length of quality sequence and length of read do not match (&#37;d+&#37;d!=&#37;d)" &#37; (len(qualities), lengthdiff, len(sequence)))
                    ValueError: Length of quality sequence and length of read do not match (22+0!=45) What version of the product are you using? On what operating system? on redhat linux.  Only crashes with -b option so far

python 2.7.2

Ran fine for most of data

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=40_

**Comment by marcelm** [comment]
_From [modockes...@gmail.com](https://code.google.com/u/112757713298074552037/) on April 02, 2012 12:52:23_

Probably my problem! Ignore this

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on April 02, 2012 23:27:09_

Perhaps I should make those error messages a little more obvious. It is -- as you seem to have guessed yourself -- an error message that points to an error in the input files, not to a crash in cutadapt.

I'll close this bug report then. Please open a new issue if you find another problem.

**Status:** Invalid
