### ISSUE TITLE
--wildcard-file throws IndexError: string index out of range

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#56]
_From [trgibbons](https://code.google.com/u/trgibbons/) on June 17, 2012 06:45:02_

What steps will reproduce the problem? 1. Run cutadapt on a large fastq file (>100k sequences) with the --wildcard-file flag set What is the expected output? What do you see instead? I expected a file containing a list of multiplexing sequence tags.
Instead I keep getting some variation of this (only paths change):
Traceback (most recent call last):
  File "/usr/local/bin/cutadapt", line 708, in \<module>
    sys.exit(main())
  File "/usr/local/bin/cutadapt", line 678, in main
    read, trimmed = cutter.cut(read)
  File "/usr/local/bin/cutadapt", line 448, in cut
    if adap_match[i] == 'N']
IndexError: string index out of range What version of the product are you using? On what operating system? Using cutadapt version 1.0 on Ubuntu 10.10 (Python 2.6) & OS X 10.7 (Python 2.7) Please provide any additional information below. Reproducible with multiple read sets, with Python 2.6 & 2.7, with installation from easy_install and from source, and on Ubuntu and OS X.

I've been running cutadapt in a shell script with a large number of flags set simultaneously.  Of these, the wildcard file flag seems to be the only one giving me trouble.

my_script.sh
\#!/bin/bash

time nice -n 12 cutadapt \
  --format=fastq \
  --anywhere=GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG \
  --output=${1&#37;.fastq}-cutadapt_q30m25_clean.fastq \
  --rest-file=${1&#37;.fastq}-cutadapt_q30m25_garbage.fastq \
  --wildcard-file=${1&#37;.fastq}-cutadapt_q30m25_tag.fastq \
  --too-short-output=${1&#37;.fastq}-cutadapt_q30m25_short.fastq \
  --untrimmed-output=${1&#37;.fastq}-cutadapt_q30m25_noadapt.fastq \
  --quality-cutoff=20 \
  --minimum-length=25 \
  $1 \
  \> ${1&#37;.fastq}-cutadapt_q30m25.log

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=46_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on June 17, 2012 10:21:01_

Could you make a (small) FASTQ file available to me that causes this, so I can reliable reproduce the problem?

**Comment by marcelm** [comment]
_From [trgibbons](https://code.google.com/u/trgibbons/) on June 17, 2012 12:28:29_

Marcel,

I've contacted our collaborators for permission to share larger files.  For
now, I did a manual binary search to track down a specific sequence from
one of the files that is able to reproduce the error:

@HWI-ST797:140:C0A89ACXX:3:1101:6462:1900 2:N:0:TAGCTT
GTCACATTCTTAAGCGCCCCGAGGGTGTACCCTTTTCCGCCGGCGTGGGGGAAGACCAGGCCTTGGGAAAGAAAATCGAGAACTCCCTGACGCCTAGTTAG
+
@@@DFFFDBHFF#########################################################################################

The long string of # jumped out at me, so I searched through some other
files that had broken cutadapt, and discovered an apparent pattern.  It
seems that low-quality reads with quality scores comprised *mostly* though
not *completely* of # break cutadapt.  I've attached a few more examples.
 The sequences in 1_1-break_cutadapt.fastq and L1P_2-break_cutadapt.fastq
have quality scores comprised completely of #, and so do not break cutadapt.

Good luck,
Ted

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on June 18, 2012 02:07:08_

Thank you, I could reproduce the problem here, so you don’t need to share the large files. I’ve fixed the problem now. It was caused by some indexing problems that were apparent only on very short reads and therefore occurred only when the reads were quality trimmed.

I’m going to release cutadapt 1.1 shortly, which will contain the fix. In the meantime, you can get the source code instead.

**Status:** Fixed
