### ISSUE TITLE
Error ELFCLASS64

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#58]
_From [evalles...@gmail.com](https://code.google.com/u/110838395153124967693/) on July 09, 2012 13:41:19_

Hello, I'm really struggling with Cutadapt... I don't know how to continue with this error:

[sudo] password for genmed13:
SIOCADDRT: El archivo ya existe
genmed13@genmed13-HP-Compaq-dc5800-Microtower:~$ cd Descargas/
genmed13@genmed13-HP-Compaq-dc5800-Microtower:~/Descargas$ cd cutadapt-1.0
genmed13@genmed13-HP-Compaq-dc5800-Microtower:~/Descargas/cutadapt-1.0$ ./cutadapt --help
Traceback (most recent call last):
  File "./cutadapt", line 78, in \<module>
    from cutadapt import align, seqio
  File "/home/genmed13/Descargas/cutadapt-1.0/lib/cutadapt/align.py", line 222, in \<module>
    from cutadapt.calign import globalalign, globalalign_locate
ImportError: /home/genmed13/Descargas/cutadapt-1.0/lib/cutadapt/calign.so: wrong ELF class: ELFCLASS64
genmed13@genmed13-HP-Compaq-dc5800-Microtower:~/Descargas/cutadapt-1.0$ python setup.py build_ext -i
running build_ext
genmed13@genmed13-HP-Compaq-dc5800-Microtower:~/Descargas/cutadapt-1.0$ ./cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC /Escritorio/s_G1_L001_I1_001_mate1.fastq -o /Escritorio/s_G1_L001_I1_001_mate1_trimmed.fastq
Traceback (most recent call last):
  File "./cutadapt", line 78, in \<module>
    from cutadapt import align, seqio
  File "/home/genmed13/Descargas/cutadapt-1.0/lib/cutadapt/align.py", line 222, in \<module>
    from cutadapt.calign import globalalign, globalalign_locate
ImportError: /home/genmed13/Descargas/cutadapt-1.0/lib/cutadapt/calign.so: wrong ELF class: ELFCLASS64

What can I do?

Thanks...

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=48_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on July 09, 2012 06:33:08_

Please try to delete the calign.so file and re-run the build_ext command line.

**Comment by marcelm** [comment]
_From [evalles...@gmail.com](https://code.google.com/u/110838395153124967693/) on July 10, 2012 03:26:33_

Done... but...

genmed13@genmed13:~/cutadapt-1.0$ ./cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC /Desktop/FastqFiles/s_G1_L001_I1_001.fastq -o /Desktop/FastqFiles/s_G1_L001_I1_001_trimmed.fastq 
Traceback (most recent call last):
  File "./cutadapt", line 78, in \<module>
    from cutadapt import align, seqio
  File "/home/genmed13/cutadapt-1.0/lib/cutadapt/align.py", line 222, in \<module>
    from cutadapt.calign import globalalign, globalalign_locate
ImportError: No module named calign


Thanks!

**Comment by marcelm** [comment]
_From [evalles...@gmail.com](https://code.google.com/u/110838395153124967693/) on July 10, 2012 03:31:26_

Sorry, you said and re-run the build_ext command line...

genmed13@genmed13:~/cutadapt-1.0$ python setup.py build_ext -irunning build_ext
building 'cutadapt.calign' extension
creating build
creating build/temp.linux-i686-2.7
creating build/temp.linux-i686-2.7/lib
creating build/temp.linux-i686-2.7/lib/cutadapt
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c lib/cutadapt/calignmodule.c -o build/temp.linux-i686-2.7/lib/cutadapt/calignmodule.o
lib/cutadapt/calignmodule.c:23:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on July 10, 2012 04:44:44_

Please see here: https://code.google.com/p/cutadapt/wiki/documentation#gcc_failed_with_exit_status_1 In short: Install the python-dev package.

I'll add this to the README as well (the FAQ is quite well hidden I admit).

**Comment by marcelm** [comment]
_From [evalles...@gmail.com](https://code.google.com/u/110838395153124967693/) on July 11, 2012 01:47:41_

I've fixed it! thanks!!

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on July 11, 2012 03:26:32_

Glad I could help :-)

**Status:** Done
