### ISSUE TITLE
AssertionError when using cutadapt --json in cutadapt 4.2

### ISSUE THREAD

**Issue by devin-AK** [marcelm/cutadapt#662]
Thank you for the work you do on this tool. I love cutadapt. 

However, I have an issue using the --json reporting feature with cutadapt 4.2 (Python 3.10.8). Cutadapt was installed using conda (the same issue is also in a singularity image with cutadapt v 4.1 Python 3.10.6).

When I run cutadapt as follows for the demulitplexing step in a pipeline:
```
cutadapt --debug --no-indels --discard-untrimmed -g file:${adapters} -G AGATGTGTATAAGAGACAG -o fastq/{name}.R1.fastq -p fastq/{name}.R2.fastq R1_trim.fastq R2_trim.fastq
```
The command completes without error. Here is a snippet of the output:
```
Processing paired-end reads on 1 core ...
DEBUG: Opening 'R1_trim.fastq', mode 'rb' with xopen resulted in <_io.BufferedReader name='R1_trim.fastq'>
DEBUG: Opening 'R2_trim.fastq', mode 'rb' with xopen resulted in <_io.BufferedReader name='R2_trim.fastq'>
DEBUG: Pipeline step 1: <cutadapt.steps.PairedDemultiplexer object at 0x7fa3f9686830>
Finished in 1.223 s (13.340 µs/read; 4.50 M reads/minute).

=== Summary ===

Total read pairs processed:             91,707
  Read 1 with adapter:                  10,942 (11.9%)
  Read 2 with adapter:                  63,982 (69.8%)
Pairs written (passing filters):        10,942 (11.9%)

Total basepairs processed:    23,559,746 bp
  Read 1:    11,647,809 bp
  Read 2:    11,911,937 bp
Total written (filtered):      2,324,134 bp (9.9%)
  Read 1:     1,167,292 bp
  Read 2:     1,156,842 bp

```
However, when I run the exact same command on the same inputs, but try to enable json reporting, an assertion error occurs as shown below:
```
cutadapt --json demux.cutadapt.json --debug --no-indels --discard-untrimmed -g file:${adapters} -G AGATGTGTATAAGAGACAG -o fastq/{name}.R1.fastq -p fastq/{name}.R2.fastq R1_trim.fastq R2_trim.fastq
```
```
Processing paired-end reads on 1 core ...
DEBUG: Opening 'R1_trim.fastq', mode 'rb' with xopen resulted in <_io.BufferedReader name='R1_trim.fastq'>
DEBUG: Opening 'R2_trim.fastq', mode 'rb' with xopen resulted in <_io.BufferedReader name='R2_trim.fastq'>
DEBUG: Pipeline step 1: <cutadapt.steps.PairedDemultiplexer object at 0x7f7cc096a830>
Finished in 1.257 s (13.709 µs/read; 4.38 M reads/minute).

=== Summary ===

Total read pairs processed:             91,707
  Read 1 with adapter:                  10,942 (11.9%)
  Read 2 with adapter:                  63,982 (69.8%)
Pairs written (passing filters):        10,942 (11.9%)

Total basepairs processed:    23,559,746 bp
  Read 1:    11,647,809 bp
  Read 2:    11,911,937 bp
Total written (filtered):      2,324,134 bp (9.9%)
  Read 1:     1,167,292 bp
  Read 2:     1,156,842 bp
.
.
.
[LOTS MORE REPORTING REMOVED FOR THE SAKE OF THIS POST]
.
.
.
Overview of removed sequences
length	count	expect	max.err	error counts
3	489	1432.9	0	489
4	71	358.2	0	71
5	23	89.6	0	23
6	4	22.4	0	4
7	4	5.6	0	4
16	4	0.0	1	1 3
17	4	0.0	1	4
18	84	0.0	1	61 23
19	63252	0.0	1	62801 451
20	47	0.0	1	21 26
Traceback (most recent call last):
  File "/home/devin/miniconda3/envs/tradtools2/bin/cutadapt", line 10, in <module>
    sys.exit(main_cli())
  File "/home/devin/miniconda3/envs/tradtools2/lib/python3.10/site-packages/cutadapt/__main__.py", line 1018, in main_cli
    main(sys.argv[1:])
  File "/home/devin/miniconda3/envs/tradtools2/lib/python3.10/site-packages/cutadapt/__main__.py", line 1122, in main
    json_dict = json_report(
  File "/home/devin/miniconda3/envs/tradtools2/lib/python3.10/site-packages/cutadapt/__main__.py", line 1225, in json_report
    d.update(stats.as_json(gc_content, one_line=True))
  File "/home/devin/miniconda3/envs/tradtools2/lib/python3.10/site-packages/cutadapt/report.py", line 187, in as_json
    assert written_reads + filtered_total == self.n
AssertionError

```
When I use cutadapt for a different purpose, the json reporting works:
```
cutadapt --json=log/fragment_construction.cutadapt.json \
  --cores=16 -m 50:55 -a CTGTCTCTTATACACATCTAGATCGGAAGAGCACACGTCTGAACTCCAGTCA \
  -A "CACTGCNNNNNNNNAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT;max_error_rate=0.15;min_overlap=11" \
  -o R1_trim.fastq -p R2_trim.fastq ${fastq_R1} ${fastq_R2}
```

**Comment by marcelm** [comment]
Thanks for the report! I’ll look into this.

**Comment by marcelm** [comment]
It turns out the issue occurs only when `--json` is used together with demultiplexing and `--discard-untrimmed`. This should now be fixed. Thank you again for reporting!
