### ISSUE TITLE
Option `--rename` only works in single thread mode

### ISSUE THREAD

**Issue by pontushojer** [marcelm/cutadapt#732]
Cutadapt v4.4, Python v3.9.8

I run into this `_pickle.PicklingError` when using the `--rename` option with multiple threads. The same command works fine using a single thread.

```
cutadapt -g ^CGATGCTAATCAGATCA...AAGAGTCAATAGACCATCTAACAGGATTCAGGTANNNNNNNNNNNTTATATCACGACAAGAG -e 0.1 -m 19 -M 21 --max-n 0 --rename '{id} {match_sequence}' -j 5 -o Sample1.dbs-raw.fastq.gz Sample1.fastq.gz > log_files/Sample1.cutadapt-extract-dbs.log
Traceback (most recent call last):
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/site-packages/cutadapt/cli.py", line 1061, in main_cli
    main(sys.argv[1:])
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/site-packages/cutadapt/cli.py", line 1131, in main
    stats = run_pipeline(
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/site-packages/cutadapt/runners.py", line 469, in run_pipeline
    statistics = runner.run()
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/site-packages/cutadapt/runners.py", line 342, in run
    workers, connections = self._start_workers()
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/site-packages/cutadapt/runners.py", line 337, in _start_workers
    worker.start()
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/pontus.hojer/miniconda3/envs/dbspro/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function rename at 0x10cd14f70>: attribute lookup rename on __main__ failed
```

**Comment by marcelm** [comment]
Ah, thanks! This occurs only on macOS (because multiprocessing uses the `spawn' start method instead of `fork` as on Linux). Also, I forgot to test renaming on multiple cores, which is why it wasn’t caught during CI.

Should be fixed now.
