### ISSUE TITLE
ImportError:No module named cutadapt.scripts

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#75]
_From [xinyang6...@gmail.com](https://code.google.com/u/100556821528857551979/) on June 05, 2013 13:12:33_

Hi,

I did:

cutadapt -ab GGTCATAGCTGTTTCCTG  E020002_1_A1.1.paired.fq > E020002_1_A1.1.paired.nolinker.fq

But it came out this error:

Traceback (most recent call last):
  File "/home/xin/local/bin/cutadapt", line 9, in \<module>
    from cutadapt.scripts import cutadapt
ImportError: No module named cutadapt.scripts

The cutadapt version is cutadapt-1.2.1

Any help is very appreciated!

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=65_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on June 05, 2013 05:15:55_

How did you install cutadapt? Did you run 'python setup.py install'? It seems that something is strange with your Python installation. Can you run cutadapt from within the unpacked cutadapt-1.2.1 directory? Use the command 'bin/cutadapt' to try this.

Also, your command line should have either '-a' or '-b', but not '-ab', as you wrote above.

**Comment by marcelm** [comment]
_From [xinyang6...@gmail.com](https://code.google.com/u/100556821528857551979/) on June 05, 2013 06:05:19_

Thanks a lot! I ran 'python setup.py install --prefix=~/local' to install it. It works now using 'bin/cutadapt' within cutadapt-1.2.1 directory.

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on June 05, 2013 07:29:38_

Great! I'm closing this issue then.

**Status:** WontFix

**Comment by marcelm** [comment]
_From [vrutants...@gmail.com](https://code.google.com/u/102846781710166455648/) on July 15, 2014 15:00:09_

i am trying to install cutadapt on server, (in my account) but I am getting same error. I tried your solutions, but still getting same error.
Traceback (most recent call last):
  File "./cutadapt", line 9, in \<module>
    from cutadapt.scripts import cutadapt
  File "/project/sater/softwares/cutadapt-1.4.1/cutadapt/scripts/cutadapt.py", line 74, in \<module>
    from cutadapt.adapters import Adapter, ColorspaceAdapter, BACK, FRONT, PREFIX, ANYWHERE
  File "/project/sater/softwares/cutadapt-1.4.1/cutadapt/adapters.py", line 4, in \<module>
    from cutadapt import align, colorspace
  File "/project/sater/softwares/cutadapt-1.4.1/cutadapt/align.py", line 225, in \<module>
    from cutadapt._align import globalalign_locate, compare_prefixes
ImportError: /project/sater/softwares/cutadapt-1.4.1/cutadapt/_align.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8

Please suggest some solution.

thank you

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on July 21, 2014 05:32:40_

Hi, sorry for the late reply, I wasn't working the last days.

I'm copying here from an e-mail I sent to someone else about the same problem:

cutadapt comes with a pre-compiled Python extension module, and it seems your Python version is different from the one I used to compile the module, so you will need to re-compile the module.

Please try this within the cutadapt-1.4.2 (or 1.4.1) directory:

python setup.py build_ext -i

This should rebuild the module.

The next cutadapt version will handle this more gracefully.
